### ISSUE TITLE
Dead link to Documentation 

### ISSUE THREAD

**Issue by R-Fischer47** [nathhB/nbnet#30]
Hey nathhB, 

I wanted to read the documentation since I need some extra information additionally to the examples. 
The link in the github https://nbnet.docsforge.com/ is not working anymore unfortunately. 
Would you be able to provide a new link?
Thanks!

Best, 

Richard

**Comment by nathhB** [comment]
@R-Fischer47 well, it seems that docsforce is dead... that's a bummer. I'll look for another documentation solution, in the meantime, you can look at comments in the code, maybe you can find answers there, you can also ask questions here or join the discord server.

**Comment by nathhB** [comment]
Alright, I decided to go with docsify and github pages, seems to be a nice combo. Here is a link to the documentation: https://nathhb.github.io/nbnet

The problem is that, for now, it's simply the README file... so not very interesting. The old documentation was generated based on comments in nbnet's code. I'll need to find a way to do that again with this new setup.
